name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
    - octocat
body:
    - type: markdown
      attributes:
          value: |
              ## Thanks for taking the time to fill out this bug report!

              We're sorry that you are experience an issue. So that we can help you efficiently, please fill in this form to the best your ability. The more information that you can provide the easier we will be able to help you.
    - type: dropdown
      id: framework
      attributes:
          label: Framework
          description: Which Framework are you facing issues with?
          options:
              - React
              - React (with Tailwind)
              - React Native
              - React Native (with Expo)
              - Angular
              - Flutter
              - Hardhat
              - Truffle
              - The Graph
      validations:
          required: true
    - type: textarea
      id: what-happened
      attributes:
          label: What happened?
          description: Also tell us, what did you expect to happen?
          placeholder: Tell us what you see!
          value: "A bug happened!"
      validations:
          required: true
    - type: textarea
      id: logs
      attributes:
          label: Relevant log output
          description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
          render: shell
    - type: textarea
      id: steps-to-reproduce
      attributes:
          label: Steps to reproduce
          description: Please could you provide clearly ordered steps to reproduce the issue.
          placeholder: |
              1. Login to the System
              2. Click the menu item
              3. Submit
    - type: textarea
        id: anything-else
        attributes:
            label: Anything Else?
            description: Anything else we should know about your issue?
            placeholder: eg:- System Information, Version Information.
    - type: input
      id: contact
      attributes:
          label: Contact Details
          description: |
            Links? References? Anything that will give us more context about the issue you are encountering!
            How can we get in touch with you if we need more info?
        tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
          placeholder: ex. email@example.com
      validations:
          required: false
