name: Bug Report
description: File a bug report
title: "🪳: "
body:
    - type: markdown
      attributes:
          value: |
              ## Thanks for taking the time to fill out this bug report!
    - type: textarea
      attributes:
          label: What happened?
          description: Also tell us, what did you expect to happen?
          placeholder: Tell us what you see!
    - type: textarea
      attributes:
          label: Steps to reproduce
          description: Please could you provide clearly ordered steps to reproduce the issue.
          placeholder: |
              1. Login to the System
              2. Click the Menu Item
              3. Submit
    - type: textarea
      attributes:
          label: Anything else?
          description: |
              Links? References? Anything that will give us more context about the issue you are encountering!
              Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
